### PR TITLE
fix(schema): remove left over `#\n` lines from description

### LINKED ISSUE #46: Empty comment lines include `#` when used without a trailing space
```yaml
# -- With space
# 
# Without space
#
foo: bar
```

results in the following description:
```json
"description": "With space\n\nWithout space\n#",
```

Also, having `--keep-full-comment` or not doesn't seem to make any difference here - is that intended / how exactly should this work?

Edit: Using newest helm-schema version 0.12.0.

### PR DESCRIPTION
**Pull request by outofrange**
Removing optional space after `#` line prefix
through `strings.TrimLeft`.

Exampleinput:
```yaml
# -- With space
#
# Without space
#
foo: bar
```

Instead of: `"description": "With space\n\nWithout space\n#"`
we get `"description": "With space\n\nWithout space\n"`

fixes #46

### CODE REVIEW

File: pkg/schema/schema.go [hunk 1]
```diff
@@ -435,11 +435,11 @@ func GetSchemaFromComment(comment string) (Schema, string, error) {
 			continue
 		}
 		if insideSchemaBlock {
-			content := strings.TrimPrefix(line, CommentPrefix)
-			rawSchema = append(rawSchema, strings.TrimPrefix(content, CommentPrefix))
+			content := strings.TrimLeft(strings.TrimPrefix(line, CommentPrefix), " ")
```
Comment (outofrange) [inline pkg/schema/schema.go:438]: @dadav should we rather use `string.Trim` instead of `TrimLeft` on those 3 places?

Comment (dadav) [reply pkg/schema/schema.go:438]: I think TrimLeft is fine.
